behaviors:
  DriverAgent:
    trainer_type: ppo
    summary_freq: 10000
    time_horizon: 128
    max_steps: 2000000
    keep_checkpoints: 5
    checkpoint_interval: 500000
    threaded: false
    hyperparameters:
      learning_rate: 3e-4
      batch_size: 256
      buffer_size: 5120 #5120 #20480 #2048 #4096 #40960
      learning_rate_schedule: linear
      beta: 1e-2
      epsilon: 0.2 #0.3
      beta_schedule: linear
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 8 #10
      shared_critic: false
    network_settings:
      hidden_units: 128
      num_layers: 2
      normalize: false
      vis_encode_type: simple
      conditioning_type: hyper
    reward_signals:
      extrinsic:
        strength: 1.0
        gamma: 0.99
      curiosity:
        gamma: 0.99
        strength: 0.05
        network_settings:
          hidden_units: 256
        learning_rate: 0.0003
      # gail:
      #   strength: 1.0
      #   gamma: 0.99
      #   demo_path: Assets/Demonstrations/EasyDemo.demo
      #   use_actions: true